language: python
python:
  - "2.7"
# command to install dependencies
install:
    - "echo foo >> /dev/null"

script:
    - mkdir ~/.newslynx/
    - wget https://github.com/newslynx/newslynx-core/blob/feature/modular/newslynx/dot_newslynx/config.yaml -o ~/.newslynx/config.yaml
    - cat ~/.newslynx/config.yaml


# command to run tests
# script: nosetests