language: python
python:
  - "2.7"
# command to install dependencies
install:
  - "mkdir ~/.newslynx/"
  - "wget https://raw.githubusercontent.com/newslynx/newslynx-core/master/newslynx/dot_newslynx/config.yaml -o ~/.newslynx/config.yaml"
  - "pip install --editable ."
sudo: true
# command to run tests
script: nosetests